// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcIReK0osrwIVwKZDO1OL19EWH8qnnWSQ',
    appId: '1:19900081117:web:cc3d3470a0066a29294c34',
    messagingSenderId: '19900081117',
    projectId: 'lab-test-43b8b',
    authDomain: 'lab-test-43b8b.firebaseapp.com',
    storageBucket: 'lab-test-43b8b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-nEur2SVRzUXLyZmlYgsPSRWibDPgaz4',
    appId: '1:19900081117:android:3db56d4a9e6635ee294c34',
    messagingSenderId: '19900081117',
    projectId: 'lab-test-43b8b',
    storageBucket: 'lab-test-43b8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPfi6gc1rTOUtIMpgtr5mMwmGT2nKgSLY',
    appId: '1:19900081117:ios:f5d69ebd0b35dec6294c34',
    messagingSenderId: '19900081117',
    projectId: 'lab-test-43b8b',
    storageBucket: 'lab-test-43b8b.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPfi6gc1rTOUtIMpgtr5mMwmGT2nKgSLY',
    appId: '1:19900081117:ios:f5d69ebd0b35dec6294c34',
    messagingSenderId: '19900081117',
    projectId: 'lab-test-43b8b',
    storageBucket: 'lab-test-43b8b.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcIReK0osrwIVwKZDO1OL19EWH8qnnWSQ',
    appId: '1:19900081117:web:8cdefdbd1cdfc61a294c34',
    messagingSenderId: '19900081117',
    projectId: 'lab-test-43b8b',
    authDomain: 'lab-test-43b8b.firebaseapp.com',
    storageBucket: 'lab-test-43b8b.firebasestorage.app',
  );

}